package com.model;
// Generated Jul 8, 2019 11:49:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classroom generated by hbm2java
 */
@Entity
@Table(name = "Classroom", catalog = "StudentPointManager")
public class Classroom implements java.io.Serializable {

	private int classId;
	private Course course;
	private String name;
	private String year;
	private Set<UserClass> userClasses = new HashSet<UserClass>(0);

	public Classroom() {
	}

	public Classroom(int classId, Course course, String name, String year) {
		this.classId = classId;
		this.course = course;
		this.name = name;
		this.year = year;
	}

	public Classroom(int classId, Course course, String name, String year, Set<UserClass> userClasses) {
		this.classId = classId;
		this.course = course;
		this.name = name;
		this.year = year;
		this.userClasses = userClasses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "class_id", unique = true, nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "year", nullable = false, length = 10)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classroom")
	public Set<UserClass> getUserClasses() {
		return this.userClasses;
	}

	public void setUserClasses(Set<UserClass> userClasses) {
		this.userClasses = userClasses;
	}

}
