package com.model;
// Generated Jul 8, 2019 11:49:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "Course", schema = "dbo", catalog = "StudentPointManager")
public class Course implements java.io.Serializable {

	private int courseId;
	private String name;
	private String description;
	private boolean status;
	private Set<Classroom> classrooms = new HashSet<Classroom>(0);
	private Set<Subject> subjects = new HashSet<Subject>(0);

	public Course() {
	}

	public Course(int courseId, String name, boolean status) {
		this.courseId = courseId;
		this.name = name;
		this.status = status;
	}

	public Course(int courseId, String name, String description, boolean status, Set<Classroom> classrooms,
			Set<Subject> subjects) {
		this.courseId = courseId;
		this.name = name;
		this.description = description;
		this.status = status;
		this.classrooms = classrooms;
		this.subjects = subjects;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "course_id", unique = true, nullable = false)
	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1073741823)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Classroom> getClassrooms() {
		return this.classrooms;
	}

	public void setClassrooms(Set<Classroom> classrooms) {
		this.classrooms = classrooms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

}
