package com.model;
// Generated Jul 8, 2019 11:49:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exam generated by hbm2java
 */
@Entity
@Table(name = "Exam", catalog = "StudentPointManager")
public class Exam implements java.io.Serializable {

	private int examId;
	private Subject subject;
	private String name;
	private String description;
	private String startDate;
	private boolean status;
	private Set<ExamResult> examResults = new HashSet<ExamResult>(0);

	public Exam() {
	}

	public Exam(int examId, Subject subject, String name, String startDate, boolean status) {
		this.examId = examId;
		this.subject = subject;
		this.name = name;
		this.startDate = startDate;
		this.status = status;
	}

	public Exam(int examId, Subject subject, String name, String description, String startDate, boolean status,
			Set<ExamResult> examResults) {
		this.examId = examId;
		this.subject = subject;
		this.name = name;
		this.description = description;
		this.startDate = startDate;
		this.status = status;
		this.examResults = examResults;
	}

	@Id

	@Column(name = "exam_id", unique = true, nullable = false)
	public int getExamId() {
		return this.examId;
	}

	public void setExamId(int examId) {
		this.examId = examId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1073741823)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "start_date", nullable = false, length = 10)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exam")
	public Set<ExamResult> getExamResults() {
		return this.examResults;
	}

	public void setExamResults(Set<ExamResult> examResults) {
		this.examResults = examResults;
	}

}
