package com.model;
// Generated Jul 8, 2019 11:49:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "Subject", schema = "dbo", catalog = "StudentPointManager")
public class Subject implements java.io.Serializable {

	private int subjectId;
	private Course course;
	private String name;
	private String description;
	private String image;
	private boolean status;
	private Set<Exam> exams = new HashSet<Exam>(0);

	public Subject() {
	}

	public Subject(int subjectId, Course course, String name, boolean status) {
		this.subjectId = subjectId;
		this.course = course;
		this.name = name;
		this.status = status;
	}

	public Subject(int subjectId, Course course, String name, String description, String image, boolean status,
			Set<Exam> exams) {
		this.subjectId = subjectId;
		this.course = course;
		this.name = name;
		this.description = description;
		this.image = image;
		this.status = status;
		this.exams = exams;
	}

	@Id

	@Column(name = "subject_id", unique = true, nullable = false)
	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 1073741823)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image", length = 1073741823)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<Exam> getExams() {
		return this.exams;
	}

	public void setExams(Set<Exam> exams) {
		this.exams = exams;
	}

}
