package com.model;
// Generated Jul 8, 2019 11:49:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserClassId generated by hbm2java
 */
@Embeddable
public class UserClassId implements java.io.Serializable {

	private int classId;
	private String userName;
	private boolean status;

	public UserClassId() {
	}

	public UserClassId(int classId, String userName, boolean status) {
		this.classId = classId;
		this.userName = userName;
		this.status = status;
	}

	@Column(name = "class_id", nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@Column(name = "user_name", nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserClassId))
			return false;
		UserClassId castOther = (UserClassId) other;

		return (this.getClassId() == castOther.getClassId())
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& (this.isStatus() == castOther.isStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClassId();
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (this.isStatus() ? 1 : 0);
		return result;
	}

}
