package com.model;
// Generated Jul 8, 2019 11:49:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserClass generated by hbm2java
 */
@Entity
@Table(name = "UserClass", schema = "dbo", catalog = "StudentPointManager")
public class UserClass implements java.io.Serializable {

	private UserClassId id;
	private Classroom classroom;
	private User user;

	public UserClass() {
	}

	public UserClass(UserClassId id, Classroom classroom, User user) {
		this.id = id;
		this.classroom = classroom;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "classId", column = @Column(name = "class_id", nullable = false)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 100)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false)) })
	public UserClassId getId() {
		return this.id;
	}

	public void setId(UserClassId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false, insertable = false, updatable = false)
	public Classroom getClassroom() {
		return this.classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_name", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
