package com.model;
// Generated Jul 8, 2019 11:49:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "UserRole", schema = "dbo", catalog = "StudentPointManager")
public class UserRole implements java.io.Serializable {

	private UserRoleId id;
	private Role role;
	private UserData user;
	private boolean status;

	public UserRole() {
	}

	public UserRole(UserRoleId id, Role role, UserData user, boolean status) {
		this.id = id;
		this.role = role;
		this.user = user;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 100)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false, length = 50)) })
	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_name", nullable = false, insertable = false, updatable = false)
	public UserData getUser() {
		return this.user;
	}

	public void setUser(UserData user) {
		this.user = user;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
